/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/assignments`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/team-management`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/events` | `/events`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more` | `/more`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/picklist` | `/picklist`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/predictor` | `/predictor`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/scout` | `/scout`; params?: Router.UnknownInputParams; } | { pathname: `/event/[key]`, params: Router.UnknownInputParams & { key: string | number; } } | { pathname: `/team/[number]`, params: Router.UnknownInputParams & { number: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/assignments`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/team-management`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/events` | `/events`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/more` | `/more`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/picklist` | `/picklist`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/predictor` | `/predictor`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/scout` | `/scout`; params?: Router.UnknownOutputParams; } | { pathname: `/event/[key]`, params: Router.UnknownOutputParams & { key: string; } } | { pathname: `/team/[number]`, params: Router.UnknownOutputParams & { number: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/assignments${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/team-management${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/events${`?${string}` | `#${string}` | ''}` | `/events${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/more${`?${string}` | `#${string}` | ''}` | `/more${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/picklist${`?${string}` | `#${string}` | ''}` | `/picklist${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/predictor${`?${string}` | `#${string}` | ''}` | `/predictor${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/scout${`?${string}` | `#${string}` | ''}` | `/scout${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/assignments`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/team-management`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/events` | `/events`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more` | `/more`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/picklist` | `/picklist`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/predictor` | `/predictor`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/scout` | `/scout`; params?: Router.UnknownInputParams; } | `/event/${Router.SingleRoutePart<T>}` | `/team/${Router.SingleRoutePart<T>}` | { pathname: `/event/[key]`, params: Router.UnknownInputParams & { key: string | number; } } | { pathname: `/team/[number]`, params: Router.UnknownInputParams & { number: string | number; } };
    }
  }
}
